Vagrant.configure(2) do |config|
  config.vm.box = "base"
  config.vm.hostname = "bughunter"
  config.vm.provision "file", source: "sources.list.ali", destination: "sources.list"
  config.vm.provision "file", source: "go1.6.2.linux-amd64.tar.gz", destination: "go1.6.2.linux-amd64.tar.gz"
  config.vm.provision "shell", path: "bootstrap.sh"
end
