Vagrant.configure(2) do |config|
  config.vm.box = "base"
  config.vm.hostname = "mirrors"
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.provision "file", source: "sources.list.ali", destination: "sources.list"
  config.vm.provision :shell, path: "bootstrap.sh"
end
